# Generated by Django 5.2 on 2025-05-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=50, verbose_name='Descripcion')),
                ('marca', models.CharField(default='', max_length=20, verbose_name='Marca')),
                ('procedencia', models.CharField(default='', max_length=20, verbose_name='Procedencia')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('stockmaximo', models.IntegerField(default=0, verbose_name='Stock Maximo')),
                ('stockminimo', models.IntegerField(default=0, verbose_name='Stock Minimo')),
                ('imagen', models.ImageField(default='productos/default.png', upload_to='productos')),
            ],
        ),
    ]
