# Generated by Django 5.2 on 2025-05-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='imagenes/default.png', upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
