# Generated by Django 5.2 on 2025-06-29 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('nit', models.CharField(default='', max_length=20, verbose_name='Nit')),
                ('telefono', models.TextField(default='', max_length=30, verbose_name='Telefono')),
                ('correo', models.EmailField(default='', max_length=50, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nro. Compra')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(default='', max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(default='', max_length=50, verbose_name='Dirección')),
                ('correo', models.EmailField(default='', max_length=50, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='Teléfono')),
                ('direccion', models.TextField(default='', max_length=50, verbose_name='Dirección')),
                ('correo', models.EmailField(default='', max_length=50, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.compra', verbose_name='Compra')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.productos', verbose_name='Producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='empleado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.empleado', verbose_name='Empleado Responsable'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nro. Venta')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('cliente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.clientes', verbose_name='Cliente')),
                ('empleado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.empleado', verbose_name='Empleado Responsable')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.productos', verbose_name='Producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.venta', verbose_name='Venta')),
            ],
        ),
    ]
