# Generated by Django 5.2 on 2025-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_clientes_compra_empleado_proveedor_detalle_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='a_materno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido_M'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='a_paterno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido_P'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='a_materno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido_M'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='a_paterno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido_P'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(default='imagenes/default.png', upload_to='imagenes', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pagina',
            field=models.CharField(default='', max_length=50, verbose_name='PaginaWeb'),
        ),
    ]
