# Generated by Django 5.2 on 2025-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_clientes_telefono_alter_empleado_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='stockminimo',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(default='', max_length=20, verbose_name='Categoria'),
        ),
    ]
