# Generated by Django 5.2 on 2025-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_productos_stockminimo_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default='', max_length=50, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(default='', max_length=50, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='profesion',
            field=models.CharField(default='', max_length=50, verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='a_materno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='a_paterno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad reservada'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stockmaximo',
            field=models.IntegerField(default=0, verbose_name='Stock en tienda'),
        ),
    ]
