# Generated by Django 5.2 on 2025-11-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_empleado_cargo_empleado_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.IntegerField(default=0, verbose_name='Sueldo'),
        ),
    ]
