# Generated by Django 5.2 on 2025-12-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_empleado_password_empleado_sueldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='aplicacion.clientes', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='aplicacion.empleado', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('especificacion', models.TextField(max_length=100, verbose_name='Especificación')),
                ('fecha_coordinacion', models.DateTimeField(verbose_name='Fecha de coordinación')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.proyectos', verbose_name='Proyecto')),
            ],
        ),
    ]
